#!/bin/sh
cd "${0%/*}" || exit                        # run from this directory
. "${WM_PROJECT_DIR:?Source an OpenFOAM environment first}/wmake/scripts/AllwmakeParseArguments"

wmake libso src/poreCloud

#------------------------------------------------------------------------------
